# Windows编译环境
FROM python:3.9-windowsservercore

# 设置工作目录
WORKDIR /app

# 复制项目文件
COPY . .

# 安装依赖
RUN pip install -r requirements.txt

# 编译Windows版本
RUN pyinstaller videoMask_windows.spec

# 输出目录
VOLUME ["/app/dist"]